### ISSUE TITLE
WebStromなどのIntelliJ系のIDEでも使えると嬉しい

### ISSUE THREAD

**Issue by eretica** [hand-dot/react-inspector#1]
素敵な拡張機能をありがとうございます！

WebStormでも使えるようになると凄く嬉しいです！

**Comment by hand-dot** [comment]
要望ありがとうございます。
こちら設定ページから設定できるように修正をかけたいと思います。しばしお待ちください！

**Comment by hand-dot** [comment]
ref: https://twitter.com/labelmake/status/1567422645066661888

**Comment by hand-dot** [comment]
@eretica 
先ほど修正したものをレビューに出しました...!
![CleanShot 2022-09-10 at 12 33 50](https://user-images.githubusercontent.com/24843808/189467117-bba7ea68-d022-42ef-9c50-6ca0fa67febf.png)
2,3日でアップデートしたものがご利用いただけるかと思います。

オプションページへ遷移すると
![CleanShot 2022-09-10 at 12 39 12](https://user-images.githubusercontent.com/24843808/189467251-cf66dd7d-ade5-4f90-ac36-484123346a8b.png)

下記のオプションページにて任意のエディターへのリンクを設定できるようになっております。
![CleanShot 2022-09-10 at 12 40 44](https://user-images.githubusercontent.com/24843808/189467283-36cb9664-3423-4ac4-97eb-d48c0f70d7c3.png)

WebStromなどのIntelliJ系のIDEを使っていないのでデバッグができなかったのですが、もしURLがわかったらこのイシューにて報告していただけないでしょうか？設定例として紹介したいと思っています。

**Comment by yuanzhhh** [comment]
> @eretica 先ほど修改したものをレビューに出しました...！ 2,3日でアップデートしたものがご利用いただけるかと思います。 ![CleanShot 2022-09-10 在 12 33 50](https://user-images.githubusercontent.com/24843808/189467117-bba7ea68-d022-42ef-9c50-6ca0fa67febf.png)
> 
> オプションページへ迁移すると ![CleanShot 2022-09-10 在 12 39 12](https://user-images.githubusercontent.com/24843808/189467251-cf66dd7d-ade5-4f90-ac36-484123346a8b.png)
> 
> 下记のオプションページにててエディターへのリンクを设定できるようになっております。 ![CleanShot 2022-09-10 在 12 40 44](https://user-images.githubusercontent.com/24843808/189467283-36cb9664-3423-4ac4-97eb-d48c0f70d7c3.png)
> 
> webStromなどなど系IDEををををてないのでデバッグがなかったのですのですがががもしもしもしもしもしがががわかったらたらこのイシューイシューにて报告ししてていただけいただけいただけないないうううか

Open the URL example of webstrom:
jetbrains://web-storm/navigate/reference?project={Project name}&path=src/index.tsx:112:29

Hope to support webstrom, thanks！！！

**Comment by hand-dot** [comment]
Hi @yuanzhhh 
Thanks!

WebStrom user, Please use the below open in editor url.
```
jetbrains://web-storm/navigate/reference?project={Project name}&path=src/index.tsx:112:29
```

**Comment by eretica** [comment]
@hand-dot ありがとうございます！！！

> jetbrains://web-storm/navigate/reference?project={Project name}&path=src/index.tsx:112:29

こちらでも上記のフォーマットで開くとToolbox経由でエディタが開けるの確認できました！
拡張機能のアップーデートが反映されるの楽しみにF5しまくります！
