### ISSUE TITLE
Path does not exist エラー

### ISSUE THREAD

**Issue by pseuxide** [hand-dot/react-inspector#2]
以下のように、`path/to/file:x:undefined` にjumpしようとしてエラーが起きます。
このページがただのReactではなく、React on Railsで動いているのが原因かもしれません。

<img width="260" alt="スクリーンショット 2022-09-07 12 29 46" src="https://user-images.githubusercontent.com/33578715/188782509-22618402-6999-43d4-864d-2867eb43214f.png">

---

Reactのみで動いているページでは正常に動きます。
素晴らしい拡張機能ありがとうございます。

**Comment by hand-dot** [comment]
ご報告ありがとうございます！
こちらundefindの時のハンドリングをするように修正してアップデートかけますね！
対応して審査に出したらクローズさせていただきます。

**Comment by pseuxide** [comment]
早速の返信ありがとうございます！
楽しみにしています :slightly_smiling_face:

**Comment by hand-dot** [comment]
@pseuxide 
先ほど修正したものをレビューに出しました...!
![CleanShot 2022-09-10 at 12 33 50](https://user-images.githubusercontent.com/24843808/189467117-bba7ea68-d022-42ef-9c50-6ca0fa67febf.png)
2,3日でアップデートしたものがご利用いただけるかと思います。

#1 と合わせて修正しておりまして、
https://github.com/hand-dot/react-inspector/blob/776b5b1beecc19de9c5260bc04ca12005b662021/src/utils.ts#L40
のように `undefined` ではなく`0`でエディターに渡すようにしております。

もし不具合があればまた教えていただけると嬉しいです。
